big changes

diff --git a/build_menu b/build_menu
--- a/build_menu
+++ b/build_menu
@@ -9,6 +9,7 @@ export OUT_DIR="$DIR/out"
 export PARENT_DIR="$(readlink -f "$DIR/..")"
 export RDIR="$(pwd)"
 export MGB="$RDIR"/magiskboot
+export RAMDISK_DIR=/home/chanz22/Documentos/GitHub/android_kernel_samsung_r11s/magiskboot/ramdisk_extracted/out_dlkm/lib/modules
 
 export CROSS_COMPILE="$PARENT_DIR/clang-r416183b/bin/aarch64-linux-gnu-"
 export CC="$PARENT_DIR/clang-r416183b/bin/clang"
@@ -20,6 +21,8 @@ export LLVM=1 LLVM_IAS=1
 export ARCH=arm64
 export KERNEL_MAKE_ENV="LOCALVERSION=-v1.0"
 export KBUILD_BUILD_USER="Chanz22"
+
+export BOARD=SRPWC28A007
 
 # update git submodules
 git submodule init && git submodule update
@@ -125,21 +128,194 @@ anykernel3() {
 }
 
 build_vendor_boot() {
-  if [ -e "$MGB/images/vendor_boot/vendor_boot.img" ]; then
-    cd "$MGB" || exit
-    cp "$MGB/images/vendor_boot/vendor_boot.img" vendor_boot.img
-    ./magiskboot unpack vendor_boot.img
-    rm -rf dtb
-    cp "$DIR/out/dtb.img" dtb
-    ./magiskboot repack vendor_boot.img
-    mv "$MGB/new-boot.img" "$OUT_DIR/vendor_boot-$(date '+%Y_%m_%d').img"
-    echo "vendor_boot done!"
-    ./magiskboot cleanup
-    cd "$DIR" || exit
-    read -p "Press enter to continue..."
-  else
-    read -p "Error!" "the vendor_boot was not found in the specified path! Press enter to continue..."
+  echo "${BOLD_GREEN}***** Building vendor_boot image *****${RESET}"
+  
+  # Verificar se o vendor_boot.img original existe
+  if [ ! -e "$MGB/images/vendor_boot/vendor_boot.img" ]; then
+    echo "${BOLD_RED}[!] Error: vendor_boot.img not found at $MGB/images/vendor_boot/vendor_boot.img${RESET}"
+    pause "return to main menu"
+    return
   fi
+
+  cd "$MGB" || exit
+  
+  # Clean up previous work
+  ./magiskboot cleanup 2>/dev/null || true
+  
+  # Copy and unpack vendor_boot
+  cp "$MGB/images/vendor_boot/vendor_boot.img" vendor_boot.img
+  if ! ./magiskboot unpack vendor_boot.img; then
+    echo "${BOLD_RED}[!] Error: Failed to unpack vendor_boot.img${RESET}"
+    cd "$DIR" || exit
+    pause "return to main menu"
+    return
+  fi
+
+  # Replace dtb
+  rm -f dtb
+  if [ -e "$DIR/out/dtb.img" ]; then
+    cp "$DIR/out/dtb.img" dtb
+    echo "[*] DTB replaced successfully"
+  else
+    echo "${BOLD_RED}[!] Warning: dtb.img not found at $DIR/out/dtb.img${RESET}"
+  fi
+
+  # Repack vendor_boot
+  if ./magiskboot repack vendor_boot.img; then
+    # Move the new image to output directory
+    mkdir -p "$OUT_DIR"
+    mv "$MGB/new-boot.img" "$OUT_DIR/vendor_boot-$(date '+%Y%m%d').img"
+    echo "${BOLD_GREEN}[+] vendor_boot image created successfully!${RESET}"
+    echo "[*] Output: $OUT_DIR/vendor_boot-$(date '+%Y%m%d').img"
+  else
+    echo "${BOLD_RED}[!] Error: Failed to repack vendor_boot.img${RESET}"
+  fi
+
+  ./magiskboot cleanup
+  cd "$DIR" || exit
+  pause "continue"
+}
+
+build_modules() {
+    MODULES_FOLDER=modules
+    rm -rf out/$MODULES_FOLDER
+    mkdir build/out/$MODEL/modules_dlkm
+
+    echo "-----------------------------------------------"
+    echo "Building modules..."
+    # Strip modules and place them in modules folder
+    make ${MAKE_ARGS} INSTALL_MOD_PATH=$MODULES_FOLDER INSTALL_MOD_STRIP=1 modules_install || abort
+
+    # List of kernel modules to remove
+    # Some of the kernel modules are in /vendor_dlkm or /vendor/lib/modules and not in vendor_boot
+    # So we will remove them from the folder and run depmod again to update the files
+    # TODO: Generate a /vendor_dlkm partition as well
+    # The filenames were fetched from vendor_module_list_s5e9925.cfg and vendor_module_list_s5e9925_b0s.cfg.
+    FILENAMES="
+    sec_debug_coredump.ko
+    fingerprint.ko
+    fingerprint_sysfs.ko
+    input_booster_lkm.ko
+    dhd.ko
+    wlan.ko
+    "
+    for FILENAME in $FILENAMES; do
+        FILE=$(find out/$MODULES_FOLDER -type f -name "$FILENAME")
+        cp "$FILE" "build/out/r11s/modules_dlkm" 2>/dev/null
+        rm -f "$FILE"
+    done
+
+    # Now we run depmod to update the dep/softdep files
+    # For this we need the kernel version
+    KERNEL_DIR_PATH=$(find "out/$MODULES_FOLDER/lib/modules" -maxdepth 1 -type d -name "5.10*") || abort
+    KERNEL_VERSION=$(basename $KERNEL_DIR_PATH) || abort
+
+    # And finally depmod itself
+    depmod -a -b out/$MODULES_FOLDER $KERNEL_VERSION || abort
+
+    # depmod updates modules.alias, modules.dep and modules.softdep
+    # But the module order is not updated by depmod
+    # We have to remove the filenames ourselves
+    # But first, our vendor_boot needs modules.order definitions that go like:
+    # fingerprint.ko
+    # Clang generates modules.order definitions like this
+    # kernel/drivers/fingerprint/fingerprint.ko
+    # So we sed the file to adapt
+    sed -i 's/.*\///g' $KERNEL_DIR_PATH/modules.order 
+
+    # Now we sed the bad filenames out of the file with a loop
+    for FILENAME in $FILENAMES; do
+        sed -i "/$FILENAME/d" "$KERNEL_DIR_PATH/modules.order"
+    done
+
+    # Now we have to order the modules
+    # Samsung was nice enough to give us the order in vendor_boot_module_order_s5e9925.cfg
+    # exynos-chipid_v2.ko exynos-reboot.ko sec_debug_base_early.ko clk_exynos.ko exynos_mct_v2.ko s3c2410_wdt.ko sec_debug_mode.ko
+    # These files have to be at the top of modules.order in this order, and then we can keep the default order.
+    # Samsung wants the file to be renamed to modules.load anyways, so we will craft our own modules.load file based on modules.order
+    touch $KERNEL_DIR_PATH/modules.load
+
+    INITIAL_ORDER="
+    exynos-chipid_v2.ko
+    exynos-reboot.ko
+    sec_debug_base_early.ko
+    clk_exynos.ko
+    exynos_mct_v2.ko
+    s3c2410_wdt.ko
+    sec_debug_mode.ko
+    "
+
+    # First we add the order from Samsung into our new modules.load
+    # And we sed it out of modules.order
+    for LINE in $INITIAL_ORDER; do
+        echo $LINE >> $KERNEL_DIR_PATH/modules.load
+        sed -i "/$LINE/d" "$KERNEL_DIR_PATH/modules.order"
+    done
+
+    # Now we add the remaining lines from modules.order into modules.load
+    while IFS= read -r line; do
+        echo "$line" >> "$KERNEL_DIR_PATH/modules.load"
+    done < "$KERNEL_DIR_PATH/modules.order"
+
+    # Now we have to also modify modules.dep
+    # Android generates them like this
+    # kernel/drivers/dma/samsung-dma.ko: kernel/drivers/dma/pl330.ko
+    # But Samsung wants them like this
+    # /lib/modules/samsung-dma.ko: /lib/modules/pl330.ko
+    # So we will format it with sed
+    sed -i 's/\(kernel\/[^: ]*\/\)\([^: ]*\.ko\)/\/lib\/modules\/\2/g' "$KERNEL_DIR_PATH/modules.dep"
+
+    # Now the modules and their configuration descriptor files are ready, we move them to a folder and create the new second ramdisk
+    # The second ramdisk should contain a /lib/modules where the modules are located
+    mkdir -p build/out/r11s/modules/lib/modules
+
+    find $KERNEL_DIR_PATH -name '*.ko' -exec cp '{}' build/out/r11s/modules/lib/modules ';'
+
+    # We also copy the module configuration descriptors
+    cp $KERNEL_DIR_PATH/modules.{alias,dep,softdep,load} build/out/r11s/modules/lib/modules
+}
+
+build_vendor_boot() {
+    echo "-----------------------------------------------"
+    echo "Building vendor_boot RAMDisks..."
+    # Copy common vendor_ramdisk00 files to build/out
+    cp -a build/ramdisk/vendor_boot/ramdisk00 build/out/r11s/vendor_ramdisk00
+    
+    # Copy device firmware files for vendor_ramdisk00
+    cp -a build/ramdisk/vendor_boot/vendor_firmware/r11s/* build/out/r11s/vendor_ramdisk00
+
+    # Pack RAMDisks
+    # vendor_ramdisk == ramdisk00
+    # modules_ramdisk == ramdisk01
+    pushd build/out/$MODEL/vendor_ramdisk00 > /dev/null
+    find . ! -name . | LC_ALL=C sort | cpio -o -H newc -R root:root | lz4 -l > ../$MODEl/vendor_ramdisk || abort
+    popd > /dev/null
+
+    pushd build/out/$MODEL/modules > /dev/null
+    find . ! -name . | LC_ALL=C sort | cpio -o -H newc -R root:root | lz4 -l > ../modules_ramdisk || abort
+    popd > /dev/null
+
+    echo "-----------------------------------------------"
+    echo "Building vendor_boot image..."
+
+    OUTPUT_FILE=build/out/r11s/vendor_boot.img
+    DTB_PATH=build/out/r11s/dtb.img
+    BOOTCONFIG_PATH=build/ramdisk/bootconfig
+    RAMDISK_00=build/out/r11s/vendor_ramdisk
+    RAMDISK_01=build/out/r11s/modules_ramdisk
+    HEADER_VERSION=4
+    BASE=0x00000000
+    PAGESIZE=0x00001000
+    KERNEL_OFFSET=0x10008000
+    RAMDISK_OFFSET=0x14000000
+    TAGS_OFFSET=0x10000000
+    DTB_OFFSET=0x0000000011F00000
+    CMDLINE="bootconfig loop.max_part=7"
+
+    python3 toolchain/mkbootimg/mkbootimg.py --header_version $HEADER_VERSION --pagesize $PAGESIZE --base $BASE --kernel_offset $KERNEL_OFFSET \
+	--ramdisk_offset $RAMDISK_OFFSET --tags_offset $TAGS_OFFSET --dtb_offset $DTB_OFFSET --vendor_cmdline "$CMDLINE" --board $BOARD --dtb $DTB_PATH  \
+	--ramdisk_type 1 --ramdisk_name "" --vendor_ramdisk_fragment $RAMDISK_00 --vendor_bootconfig $BOOTCONFIG_PATH --ramdisk_type 3 \
+	--ramdisk_name dlkm --vendor_ramdisk_fragment $RAMDISK_01 --vendor_boot $OUTPUT_FILE || abort
 }
 
 build_boot_image() {
@@ -180,9 +356,10 @@ show_menus() {
   echo " 2. ${UNDERLINE}Clean${RESET} directories"
   echo " 3. Create ${UNDERLINE}Flashable ZIP${RESET}"
   echo " 4. Generate ${UNDERLINE}vendor_boot image${RESET}"
-  echo " 5. Generate ${UNDERLINE}boot image${RESET}"
-  echo " 6. ${UNDERLINE}Install Build Dependencies${RESET}"
-  echo " 7. ${UNDERLINE}Exit${RESET}"
+  echo " 5. update ${UNDERLINE}vendor_dlmk.cpio${RESET}"
+  echo " 6. Generate ${UNDERLINE}boot image${RESET}"
+  echo " 7. ${UNDERLINE}Install Build Dependencies${RESET}"
+  echo " 8. ${UNDERLINE}Exit${RESET}"
 }
 
 read_options() {
@@ -193,9 +370,10 @@ read_options() {
     2) clean ;;
     3) anykernel3 ;;
     4) build_vendor_boot ;;
-    5) build_boot_image ;;
-    6) install_dependencies ;;
-    7) exit 0 ;;
+    5) update_vendor_dlkm ;;
+    6) build_boot_image ;;
+    7) install_dependencies ;;
+    8) exit 0 ;;
     *) pause "return to menu" "Invalid option! " ;;
   esac
 }
